### PR TITLE
Added config option for changing index lock file path

### PR DESCRIPTION
**Pull request by lcharkiewicz**
Added possibility to change value of FILE_LOCK constant in config (at the same level as search_index option).

### CODE REVIEW

**Comment by pkittenis** [comment]
Hi there, thanks for the interest and the PR.

This was missing, thanks for the addition. Could you put an example entry in the example config? Looks good for merging otherwise.

**Comment by lcharkiewicz** [comment]
Hey,
I've added the example configuration also for search_index. Wanted to make it clear enough. :)

**Comment by pkittenis** [comment]
Oh, just realised that. Since it's an influxgraph configuration setting, it should be under `influxgraph` section in config, if you don't mind making that change.

**Comment by lcharkiewicz** [comment]
Sure, moved it to the `influxdb` section (I assumed you meant that one). If should be in a new,  `influxgraph` section I'll move it.

**Comment by pkittenis** [comment]
Thanks! The code is currently failing the `flake8` check - https://travis-ci.org/InfluxGraph/influxgraph/jobs/263538155

**Comment by pkittenis** [comment]
Looks great, thanks for the contribution!

**Pull request merged**
